################################################################################
#
# netatalk
#
################################################################################

NETATALK_SITE = http://downloads.sourceforge.net/project/netatalk/netatalk
NETATALK_AUTORECONF = YES
NETATALK_CONFIG_SCRIPTS = netatalk-config
NETATALK_DEPENDENCIES = host-pkgconf openssl berkeleydb libgcrypt libgpg-error \
	libevent
NETATALK_LICENSE = GPL-2.0+, LGPL-3.0+, MIT-like
NETATALK_LICENSE_FILES = COPYING COPYRIGHT

# Don't run ldconfig!
NETATALK_CONF_ENV += CC="$(TARGET_CC) -std=gnu99" \
	ac_cv_path_NETA_LDCONFIG=""
NETATALK_CONF_OPTS += \
	--with-cnid-cdb-backend \
	--with-bdb=$(STAGING_DIR)/usr \
	--with-ssl-dir=$(STAGING_DIR)/usr \
	--with-libgcrypt-dir=$(STAGING_DIR)/usr \
	--with-shadow \
	--disable-shell-check \
	--without-kerberos \
	--without-pam \
	--with-libevent=no \
	--with-dtrace=no \
	--with-mysql-config=no

ifeq ($(BR2_PACKAGE_ACL),y)
NETATALK_DEPENDENCIES += acl
else
NETATALK_CONF_OPTS += --with-acls=no
endif

ifeq ($(BR2_PACKAGE_AVAHI_DAEMON)$(BR2_PACKAGE_DBUS),yy)
NETATALK_DEPENDENCIES += avahi
NETATALK_CONF_OPTS += --enable-zeroconf=$(STAGING_DIR)/usr
else
NETATALK_CONF_OPTS += --disable-zeroconf
endif

ifeq ($(BR2_PACKAGE_CUPS),y)
NETATALK_DEPENDENCIES += cups
NETATALK_CONF_ENV += ac_cv_path_CUPS_CONFIG=$(STAGING_DIR)/usr/bin/cups-config
NETATALK_CONF_OPTS += --enable-cups
else
NETATALK_CONF_OPTS += --disable-cups
endif

# binaries to keep or remove
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_A2BOOT) += a2boot
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_ATFUNCS) += ad
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_APPLETAK) += aecho
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_APPLETAK) += getzones
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_APPLETAK) += nbp
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_APPLETAK) += pap
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_APPLETAK) += psorder
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_APPLETAK) += printing
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += adv1tov2
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += afppasswd
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += afpldaptest
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += afpstats
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += apple_dump
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += asip-status.pl
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += cnid
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += cnid2_create
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += dbd
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += megatron
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += unbin
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += unhex
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += unsingle
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += hqx2bin
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += single2bin
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += macbinary
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += macusers
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += binheader
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += nadheader
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += uniconv
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_BINARIES) += lp2pap.sh
NETATALK_BINTARGETS_$(BR2_PACKAGE_NETATALK_TIMELORD) += timelord

define NETATALK_REMOVE_UNNEEDED_BINARIES
	rm -f $(addprefix $(TARGET_DIR)/usr/bin/, $(NETATALK_BINTARGETS_))

	for file in afppasswd afp-signature.conf AppleVolumes.default ; do \
		rm -f $(TARGET_DIR)/etc/netatalk/$$file && ln -s /tmp/netatalk/$$file $(TARGET_DIR)/etc/netatalk/$$file; \
	done
endef

NETATALK_POST_INSTALL_TARGET_HOOKS += NETATALK_REMOVE_UNNEEDED_BINARIES

$(eval $(autotools-package))
